### ISSUE TITLE
looking for more information

### ISSUE THREAD

**Issue by khalidbouziane** [TangleSpace/hydralit_components#10]
Hi Jackson,

I have seen your hydralit library, and hydralit_components, and it s really a great amazing job that you have done,
I m really interested by your work and looking for a high level cooperation.
here is my email : kbouziane.ai@gmail.com, please contact me for more details.
ie- Sorry to do it this way, as I have no other alternative to reach you.

khalid.
Regards

**Comment by TangleSpace** [comment]
Hi,

Thank you for the support and interest, I'd be happy to do some collaboration, probably be best if you can give me some idea as to how you would like to contribute, as there are many ways and there are many things that should be done that haven't been, for example, proper documentation of the complete API for one, as there is a massive amount of functionality that most people don't know exists since the documentation is missing or of low detail. 

Happy to have interest, and look forward to hearing your ideas on how you'd like to contribute. Thanks

P.S. Sorry for the late reply.
